version: '3'

services:
  backend:
    image: tu-dresden/aergia-backend
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend

  frontend:
    image: tu-dresden/aergia-frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
      - 10000:10000 # HMR Port
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app


volumes:
  node_modules: