version: '3'

services:
  backend:
    image: tu-dresden/etikedi-backend
    build:
      context: ./backend
    environment:
      DATABASE_URL: db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/etikedi/backend

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: etikedi
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: