version: '3'

services:
  backend:
    image: tu-dresden/aergia-backend
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend

  frontend:
    image: tu-dresden/aergia-frontend
    build:
      context: ./frontend
    ports:
      - 8080:8080
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app


volumes:
  node_modules: