POST http://localhost:8000/3/al-wars/start
accept: application/json
Content-Type: application/json

{
  "exp_configs": [
    {
      "QUERY_STRATEGY": "QueryInstanceUncertainty",
      "QUERY_STRATEGY_CONFIG": {
        "measure": "least_confident"
      },
      "AL_MODEL": "RandomForestClassifier"
    },
    {
      "QUERY_STRATEGY": "QueryInstanceRandom",
      "QUERY_STRATEGY_CONFIG": {
      },
      "AL_MODEL": "RandomForestClassifier"
    }
  ],
  "STOPPING_CRITERIA_VALUE": 0.9,
  "STOPPING_CRITERIA": "percent_of_unlabel",
  "BATCH_SIZE": 10
}

### check status
GET http://localhost:8000/3/al-wars/status
accept: application/json

### get diagrams
# curl -X 'GET'
#  'http://localhost:8000/3/al-wars/get_diagrams'
#  -H 'accept: application/json'
GET http://localhost:8000/3/al-wars/get_diagrams
accept: application/json

### get metrics
# curl -X 'GET'
#  'http://localhost:8000/3/al-wars/get_metrics'
#  -H 'accept: application/json'
GET http://localhost:8000/3/al-wars/get_metrics
accept: application/json

###
# curl -X 'GET'
#  'http://localhost:8000/3/al-wars/valid_strategies'
#  -H 'accept: application/json'
GET http://localhost:8000/1/al-wars/valid_strategies
accept: application/json

###








